export const Armory = {
  head: [
    {
      id: 'head_1',
      displayName: 'Morion',
      slot: 'head',
      type: 'light',
      baseName: 'Medieval_Warfare_Male_Head_1',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Head_1_Paperdoll.png',
      stats: { armorValue: 0 },
    },
    {
      id: 'head_2',
      displayName: 'Great Helm',
      slot: 'head',
      type: 'heavy',
      baseName: 'Medieval_Warfare_Male_Head_2',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Head_2_Paperdoll.png',
      stats: { armorValue: 0 },
    },
    {
      id: 'head_3',
      displayName: 'Nasal Helm',
      slot: 'head',
      type: 'light',
      baseName: 'Medieval_Warfare_Male_Head_3',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Head_3_Paperdoll.png',
      stats: { armorValue: 0 },
    },
    {
      id: 'head_4',
      displayName: 'Bascinet',
      slot: 'head',
      type: 'medium',
      baseName: 'Medieval_Warfare_Male_Head_4',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Head_4_Paperdoll.png',
      stats: { armorValue: 0 },
    },
    {
      id: 'head_5',
      displayName: 'Barbute',
      slot: 'head',
      type: 'medium',
      baseName: 'Medieval_Warfare_Male_Head_5',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Head_5_Paperdoll.png',
      stats: { armorValue: 0 },
    },
    {
      id: 'head_6',
      displayName: 'Houndskull',
      slot: 'head',
      type: 'heavy',
      baseName: 'Medieval_Warfare_Male_Head_6',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Head_6_Paperdoll.png',
      stats: { armorValue: 0 },
    },
    {
      id: 'head_7',
      displayName: 'Cloth Wrap',
      slot: 'head',
      type: 'light',
      baseName: 'Medieval_Warfare_Male_Head_7',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Head_7_Paperdoll.png',
      stats: { armorValue: 0 },
    },
    {
      id: 'head_8',
      displayName: 'Closed Helm',
      slot: 'head',
      type: 'heavy',
      baseName: 'Medieval_Warfare_Male_Head_8',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Head_8_Paperdoll.png',
      stats: { armorValue: 0 },
    },
    {
      id: 'head_9',
      displayName: 'Burgonet',
      slot: 'head',
      type: 'light',
      baseName: 'Medieval_Warfare_Male_Head_9',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Head_9_Paperdoll.png',
      stats: { armorValue: 0 },
    },
    {
      id: 'head_10',
      displayName: 'Armet',
      slot: 'head',
      type: 'heavy',
      baseName: 'Medieval_Warfare_Male_Head_10',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Head_10_Paperdoll.png',
      stats: { armorValue: 0 },
    },
  ],
  body: [
    {
      id: 'body_1',
      displayName: 'Gold Scaled Tunic',
      slot: 'body',
      type: 'light',
      baseName: 'Medieval_Warfare_Male_Tabard_1',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Tabard_1_Paperdoll.png',
      stats: { armorValue: 0 },
    },
    {
      id: 'body_2',
      displayName: 'Royal Dragon Crest Tabard',
      slot: 'body',
      type: 'medium',
      baseName: 'Medieval_Warfare_Male_Tabard_2',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Tabard_2_Paperdoll.png',
      stats: { armorValue: 0 },
    },
    {
      id: 'body_3',
      displayName: 'Dragon Crest Tabard',
      slot: 'body',
      type: 'light',
      baseName: 'Medieval_Warfare_Male_Tabard_3',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Tabard_3_Paperdoll.png',
      stats: { armorValue: 0 },
    },
    {
      id: 'body_4',
      displayName: 'Decorative Tunic',
      slot: 'body',
      type: 'medium',
      baseName: 'Medieval_Warfare_Male_Tabard_4',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Tabard_4_Paperdoll.png',
      stats: { armorValue: 0 },
    },
    {
      id: 'body_5',
      displayName: 'Cloth Tunic',
      slot: 'body',
      type: 'light',
      baseName: 'Medieval_Warfare_Male_Tabard_5',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Tabard_5_Paperdoll.png',
      stats: { armorValue: 0 },
    },
    {
      id: 'body_6',
      displayName: 'White Tunic',
      slot: 'body',
      type: 'light',
      baseName: 'Medieval_Warfare_Male_Tabard_6',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Tabard_6_Paperdoll.png',
      stats: { armorValue: 0 },
    },
    {
      id: 'body_7',
      displayName: 'Black Tunic',
      slot: 'body',
      type: 'light',
      baseName: 'Medieval_Warfare_Male_Tabard_7',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Tabard_7_Paperdoll.png',
      stats: { armorValue: 0 },
    },
    {
      id: 'body_8',
      displayName: 'Magic Tabard',
      slot: 'body',
      type: 'medium',
      baseName: 'Medieval_Warfare_Male_Tabard_8',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Tabard_8_Paperdoll.png',
      stats: { armorValue: 0 },
    },
    {
      id: 'body_9',
      displayName: 'Red Tunic',
      slot: 'body',
      type: 'light',
      baseName: 'Medieval_Warfare_Male_Tabard_9',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Tabard_9_Paperdoll.png',
      stats: { armorValue: 0 },
    },
    {
      id: 'body_10',
      displayName: 'Veteran Varangian Hauberk',
      slot: 'body',
      type: 'medium',
      baseName: 'Medieval_Warfare_Male_Top_1',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Top_1_Paperdoll.png',
      stats: { armorValue: 0 },
    },
    {
      id: 'body_11',
      displayName: 'Hardened Leather Cuirass',
      slot: 'body',
      type: 'medium',
      baseName: 'Medieval_Warfare_Male_Top_2',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Top_2_Paperdoll.png',
      stats: { armorValue: 0 },
    },
    {
      id: 'body_12',
      displayName: 'Iron-Link Mail',
      slot: 'body',
      type: 'heavy',
      baseName: 'Medieval_Warfare_Male_Top_3',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Top_3_Paperdoll.png',
      stats: { armorValue: 0 },
    },
    {
      id: 'body_13',
      displayName: 'Highland Skirmisher\'s Brigandine',
      slot: 'body',
      type: 'heavy',
      baseName: 'Medieval_Warfare_Male_Top_4',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Top_4_Paperdoll.png',
      stats: { armorValue: 0 },
    },
    {
      id: 'body_14',
      displayName: 'Veteran\'s Plated Gambeson',
      slot: 'body',
      type: 'heavy',
      baseName: 'Medieval_Warfare_Male_Top_5',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Top_5_Paperdoll.png',
      stats: { armorValue: 0 },
    },
    {
      id: 'body_15',
      displayName: 'Chainmail',
      slot: 'body',
      type: 'medium',
      baseName: 'Medieval_Warfare_Male_Top_6',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Top_6_Paperdoll.png',
      stats: { armorValue: 0 },
    },
    {
      id: 'body_16',
      displayName: 'Hunter\'s Vest',
      slot: 'body',
      type: 'medium',
      baseName: 'Medieval_Warfare_Male_Top_7',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Top_7_Paperdoll.png',
      stats: { armorValue: 0 },
    },
  ],
  bottom: [
    {
      id: 'bottom_1',
      displayName: 'Splint Greaves',
      slot: 'bottom',
      type: 'medium',
      baseName: 'Medieval_Warfare_Male_Bottom_1',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Bottom_1_Paperdoll.png',
      stats: { armorValue: 0 },
    },
    {
      id: 'bottom_2',
      displayName: 'Hardened Leather Chaps',
      slot: 'bottom',
      type: 'medium',
      baseName: 'Medieval_Warfare_Male_Bottom_2',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Bottom_2_Paperdoll.png',
      stats: { armorValue: 0 },
    },
    {
      id: 'bottom_3',
      displayName: 'Stalker\'s Trousers',
      slot: 'bottom',
      type: 'light',
      baseName: 'Medieval_Warfare_Male_Bottom_3',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Bottom_3_Paperdoll.png',
      stats: { armorValue: 0 },
    },
    {
      id: 'bottom_4',
      displayName: 'Plated Greaves',
      slot: 'bottom',
      type: 'heavy',
      baseName: 'Medieval_Warfare_Male_Bottom_4',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Bottom_4_Paperdoll.png',
      stats: { armorValue: 0 },
    },
  ],
  feet: [
    {
      id: 'feet_1',
      displayName: 'Leather Boots',
      slot: 'feet',
      type: 'light',
      baseName: 'Medieval_Warfare_Male_Feet_1',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Feet_1_Paperdoll.png',
      stats: { armorValue: 0 },
    },
    {
      id: 'feet_2',
      displayName: 'Strapped Boots',
      slot: 'feet',
      type: 'medium',
      baseName: 'Medieval_Warfare_Male_Feet_2',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Feet_2_Paperdoll.png',
      stats: { armorValue: 0 },
    },
  ],
  weapon: [
    {
      id: 'weapon_1',
      displayName: 'Matchlock Arquebus',
      slot: 'weapon',
      type: 'ranged',
      baseName: 'Medieval_Warfare_Male_Weapon_Arquebus',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Weapon_Arquebus_Paperdoll.png',
      stats: { damageValue: 0 },
    },
    {
      id: 'weapon_2',
      displayName: 'Recurve Composite Bow',
      slot: 'weapon',
      type: 'ranged',
      baseName: 'Medieval_Warfare_Male_Weapon_Bow',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Weapon_Bow_Paperdoll.png',
      stats: { damageValue: 0 },
    },
    {
      id: 'weapon_3',
      displayName: 'Soldier\'s Arming Sword',
      slot: 'weapon',
      type: 'melee',
      baseName: 'Medieval_Warfare_Male_Weapon_CrosshiltSword',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Weapon_CrosshiltSword_Paperdoll.png',
      stats: { damageValue: 0 },
    },
    {
      id: 'weapon_4',
      displayName: 'Vanguard Twin-Axe',
      slot: 'weapon',
      type: 'melee',
      baseName: 'Medieval_Warfare_Male_Weapon_Doubleaxe',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Weapon_Doubleaxe_Paperdoll.png',
      stats: { damageValue: 0 },
    },
    {
      id: 'weapon_5',
      displayName: 'Heavy Flanged Mace',
      slot: 'weapon',
      type: 'melee',
      baseName: 'Medieval_Warfare_Male_Weapon_FlangedMace',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Weapon_FlangedMace_Paperdoll.png',
      stats: { damageValue: 0 },
    },
    {
      id: 'weapon_6',
      displayName: 'Garrison Halberd',
      slot: 'weapon',
      type: 'melee',
      baseName: 'Medieval_Warfare_Male_Weapon_Halberd',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Weapon_Halberd_Paperdoll.png',
      stats: { damageValue: 0 },
    },
    {
      id: 'weapon_7',
      displayName: 'Knightly Longsword',
      slot: 'weapon',
      type: 'melee',
      baseName: 'Medieval_Warfare_Male_Weapon_Longsword',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Weapon_Longsword_Paperdoll.png',
      stats: { damageValue: 0 },
    },
    {
      id: 'weapon_8',
      displayName: 'Spiked Footman\'s Mace',
      slot: 'weapon',
      type: 'melee',
      baseName: 'Medieval_Warfare_Male_Weapon_Mace',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Weapon_Mace_Paperdoll.png',
      stats: { damageValue: 0 },
    },
    {
      id: 'weapon_9',
      displayName: 'Frontline Pike',
      slot: 'weapon',
      type: 'melee',
      baseName: 'Medieval_Warfare_Male_Weapon_Pike',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Weapon_Pike_Paperdoll.png',
      stats: { damageValue: 0 },
    },
    {
      id: 'weapon_10',
      displayName: 'Crow\'s Beak Warhammer',
      slot: 'weapon',
      type: 'melee',
      baseName: 'Medieval_Warfare_Male_Weapon_Warhammer',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Weapon_Warhammer_Paperdoll.png',
      stats: { damageValue: 0 },
    },
    {
      id: 'weapon_11',
      displayName: 'Steel-Prod Crossbow',
      slot: 'weapon',
      type: 'ranged',
      baseName: 'Medieval_Warfare_Male_Weapon_Xbow',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Weapon_XBow_Paperdoll.png',
      stats: { damageValue: 0 },
    },
    {
      id: 'weapon_12',
      displayName: 'Landsknecht Zweihander',
      slot: 'weapon',
      type: 'melee',
      baseName: 'Medieval_Warfare_Male_Weapon_Zweihander',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Weapon_Zweihander_Paperdoll.png',
      stats: { damageValue: 0 },
    },
  ],
  offhand: [
    {
      id: 'offhand_1',
      displayName: 'Parrying Arming Sword',
      slot: 'offhand',
      type: 'melee',
      baseName: 'Medieval_Warfare_Male_Weapon_CrosshiltSword',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Weapon_CrosshiltSword_Paperdoll.png',
      stats: { armorValue: 0, blockChance: 0 },
    },
    {
      id: 'offhand_2',
      displayName: 'Offhand Flanged Mace',
      slot: 'offhand',
      type: 'melee',
      baseName: 'Medieval_Warfare_Male_Weapon_FlangedMace',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Weapon_FlangedMace_Paperdoll.png',
      stats: { armorValue: 0, blockChance: 0 },
    },
    {
      id: 'offhand_3',
      displayName: 'Companion Longsword',
      slot: 'offhand',
      type: 'melee',
      baseName: 'Medieval_Warfare_Male_Weapon_Longsword',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Weapon_Longsword_Paperdoll.png',
      stats: { armorValue: 0, blockChance: 0 },
    },
    {
      id: 'offhand_4',
      displayName: 'Curb Spiked Mace',
      slot: 'offhand',
      type: 'melee',
      baseName: 'Medieval_Warfare_Male_Weapon_Mace',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Weapon_Mace_Paperdoll.png',
      stats: { armorValue: 0, blockChance: 0 },
    },
    {
      id: 'offhand_5',
      displayName: 'Royal Shield',
      slot: 'offhand',
      type: 'heavy',
      baseName: 'Medieval_Warfare_Male_Shield_1',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Shield_1_Paperdoll.png',
      stats: { armorValue: 0, blockChance: 0 },
    },
    {
      id: 'offhand_6',
      displayName: 'Buckler',
      slot: 'offhand',
      type: 'light',
      baseName: 'Medieval_Warfare_Male_Shield_2',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Shield_2_Paperdoll.png',
      stats: { armorValue: 0, blockChance: 0 },
    },
    {
      id: 'offhand_7',
      displayName: 'Aquila Kite Shield',
      slot: 'offhand',
      type: 'heavy',
      baseName: 'Medieval_Warfare_Male_Shield_3',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Shield_3_Paperdoll.png',
      stats: { armorValue: 0, blockChance: 0 },
    },
    {
      id: 'offhand_8',
      displayName: 'Green Scutum',
      slot: 'offhand',
      type: 'medium',
      baseName: 'Medieval_Warfare_Male_Shield_4',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Shield_4_Paperdoll.png',
      stats: { armorValue: 0, blockChance: 0 },
    },
    {
      id: 'offhand_9',
      displayName: 'Crusader\'s Kite Shield',
      slot: 'offhand',
      type: 'heavy',
      baseName: 'Medieval_Warfare_Male_Shield_5',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Shield_5_Paperdoll.png',
      stats: { armorValue: 0, blockChance: 0 },
    },
    {
      id: 'offhand_10',
      displayName: 'Spiked Round Shield',
      slot: 'offhand',
      type: 'light',
      baseName: 'Medieval_Warfare_Male_Shield_6',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Shield_6_Paperdoll.png',
      stats: { armorValue: 0, blockChance: 0 },
    },
    {
      id: 'offhand_11',
      displayName: 'Oak Heater Shield',
      slot: 'offhand',
      type: 'light',
      baseName: 'Medieval_Warfare_Male_Shield_7',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Shield_7_Paperdoll.png',
      stats: { armorValue: 0, blockChance: 0 },
    },
    {
      id: 'offhand_12',
      displayName: 'Oak Kite Shield',
      slot: 'offhand',
      type: 'light',
      baseName: 'Medieval_Warfare_Male_Shield_8',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Shield_8_Paperdoll.png',
      stats: { armorValue: 0, blockChance: 0 },
    },
  ],
};

export function getItemPaths(item) {
  const base = `assets/armory/${item.slot}`;
  return {
    idle:    `${base}/${item.slot}_idle/${item.baseName}_idle1_diag.png`,
    walking: `${base}/${item.slot}_walking/${item.baseName}_walking_diag.png`,
    attack1: `${base}/${item.slot}_attacking/${item.baseName}_MVsv_alt_attack1.png`,
    attack2: `${base}/${item.slot}_attacking/${item.baseName}_MVsv_alt_attack2.png`,
  };
}
