export const Armory = {
  head: [
    {
      id: 'head_1',
      displayName: 'Morion',
      slot: 'head',
      type: 'light',
      baseName: 'Medieval_Warfare_Male_Head_1',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Head_1_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Head_1_Paperdoll.png',
      stats: { armorValue: 1 },
      value: 0,
      description: 'A lightweight open-faced helmet favored by skirmishers and scouts.',
    },
    {
      id: 'head_2',
      displayName: 'Great Helm',
      slot: 'head',
      type: 'heavy',
      baseName: 'Medieval_Warfare_Male_Head_2',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Head_2_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Head_2_Paperdoll.png',
      stats: { armorValue: 1 },
      value: 0,
      description: 'A fully enclosing iron helm offering superior protection at the cost of visibility.',
    },
    {
      id: 'head_3',
      displayName: 'Nasal Helm',
      slot: 'head',
      type: 'light',
      baseName: 'Medieval_Warfare_Male_Head_3',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Head_3_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Head_3_Paperdoll.png',
      stats: { armorValue: 1 },
      value: 0,
      description: 'A simple yet effective helmet with a distinctive nose guard.',
    },
    {
      id: 'head_4',
      displayName: 'Bascinet',
      slot: 'head',
      type: 'medium',
      baseName: 'Medieval_Warfare_Male_Head_4',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Head_4_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Head_4_Paperdoll.png',
      stats: { armorValue: 1 },
      value: 0,
      description: 'A versatile visored helmet that balances protection and mobility.',
    },
    {
      id: 'head_5',
      displayName: 'Barbute',
      slot: 'head',
      type: 'medium',
      baseName: 'Medieval_Warfare_Male_Head_5',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Head_5_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Head_5_Paperdoll.png',
      stats: { armorValue: 1 },
      value: 0,
      description: 'A smooth Italian-style helm with a T-shaped facial opening.',
    },
    {
      id: 'head_6',
      displayName: 'Houndskull',
      slot: 'head',
      type: 'heavy',
      baseName: 'Medieval_Warfare_Male_Head_6',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Head_6_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Head_6_Paperdoll.png',
      stats: { armorValue: 1 },
      value: 0,
      description: 'A beaked visor helm named for its distinctive pointed snout.',
    },
    {
      id: 'head_7',
      displayName: 'Cloth Wrap',
      slot: 'head',
      type: 'light',
      baseName: 'Medieval_Warfare_Male_Head_7',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Head_7_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Head_7_Paperdoll.png',
      stats: { armorValue: 1 },
      value: 0,
      description: 'A simple wrapped cloth offering minimal protection but maximum comfort.',
    },
    {
      id: 'head_8',
      displayName: 'Closed Helm',
      slot: 'head',
      type: 'heavy',
      baseName: 'Medieval_Warfare_Male_Head_8',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Head_8_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Head_8_Paperdoll.png',
      stats: { armorValue: 1 },
      value: 0,
      description: 'A full-face enclosing battle helm with reinforced visor.',
    },
    {
      id: 'head_9',
      displayName: 'Burgonet',
      slot: 'head',
      type: 'light',
      baseName: 'Medieval_Warfare_Male_Head_9',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Head_9_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Head_9_Paperdoll.png',
      stats: { armorValue: 1 },
      value: 0,
      description: 'An open-faced cavalry helmet with a prominent brim and cheek guards.',
    },
    {
      id: 'head_10',
      displayName: 'Armet',
      slot: 'head',
      type: 'heavy',
      baseName: 'Medieval_Warfare_Male_Head_10',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Head_10_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Head_10_Paperdoll.png',
      stats: { armorValue: 1 },
      value: 0,
      description: 'A fully enclosing knightly helm with locking visor and bevor.',
    },
  ],
  body: [
    {
      id: 'body_1',
      displayName: 'Gold Scaled Tunic',
      slot: 'body',
      type: 'light',
      baseName: 'Medieval_Warfare_Male_Tabard_1',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Tabard_1_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Tabard_1_Paperdoll.png',
      stats: { armorValue: 1 },
      value: 0,
      description: 'A decorative tunic adorned with gilded scale plates.',
    },
    {
      id: 'body_2',
      displayName: 'Royal Dragon Crest Tabard',
      slot: 'body',
      type: 'medium',
      baseName: 'Medieval_Warfare_Male_Tabard_2',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Tabard_2_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Tabard_2_Paperdoll.png',
      stats: { armorValue: 1 },
      value: 0,
      description: 'A noble tabard bearing the crest of the dragon order.',
    },
    {
      id: 'body_3',
      displayName: 'Dragon Crest Tabard',
      slot: 'body',
      type: 'light',
      baseName: 'Medieval_Warfare_Male_Tabard_3',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Tabard_3_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Tabard_3_Paperdoll.png',
      stats: { armorValue: 1 },
      value: 0,
      description: 'A cloth tabard marked with the dragon heraldry of common soldiers.',
    },
    {
      id: 'body_4',
      displayName: 'Decorative Tunic',
      slot: 'body',
      type: 'medium',
      baseName: 'Medieval_Warfare_Male_Tabard_4',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Tabard_4_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Tabard_4_Paperdoll.png',
      stats: { armorValue: 1 },
      value: 0,
      description: 'A finely embroidered tunic worn by officers and nobles.',
    },
    {
      id: 'body_5',
      displayName: 'Cloth Tunic',
      slot: 'body',
      type: 'light',
      baseName: 'Medieval_Warfare_Male_Tabard_5',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Tabard_5_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Tabard_5_Paperdoll.png',
      stats: { armorValue: 1 },
      value: 0,
      description: 'A basic cloth tunic offering little protection but unrestrained movement.',
    },
    {
      id: 'body_6',
      displayName: 'White Tunic',
      slot: 'body',
      type: 'light',
      baseName: 'Medieval_Warfare_Male_Tabard_6',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Tabard_6_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Tabard_6_Paperdoll.png',
      stats: { armorValue: 1 },
      value: 0,
      description: 'A clean white tunic favored by pilgrims and healers.',
    },
    {
      id: 'body_7',
      displayName: 'Black Tunic',
      slot: 'body',
      type: 'light',
      baseName: 'Medieval_Warfare_Male_Tabard_7',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Tabard_7_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Tabard_7_Paperdoll.png',
      stats: { armorValue: 1 },
      value: 0,
      description: 'A plain black tunic worn by spies and nighttime raiders.',
    },
    {
      id: 'body_8',
      displayName: 'Magic Tabard',
      slot: 'body',
      type: 'medium',
      baseName: 'Medieval_Warfare_Male_Tabard_8',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Tabard_8_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Tabard_8_Paperdoll.png',
      stats: { armorValue: 1 },
      value: 0,
      description: 'A tabard imbued with minor enchantments that resist cutting blows.',
    },
    {
      id: 'body_9',
      displayName: 'Red Tunic',
      slot: 'body',
      type: 'light',
      baseName: 'Medieval_Warfare_Male_Tabard_9',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Tabard_9_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Tabard_9_Paperdoll.png',
      stats: { armorValue: 1 },
      value: 0,
      description: 'A vibrant red tunic that doubles as a rallying banner on the battlefield.',
    },
    {
      id: 'body_10',
      displayName: 'Veteran Varangian Hauberk',
      slot: 'body',
      type: 'medium',
      baseName: 'Medieval_Warfare_Male_Top_1',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Top_1_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Top_1_Paperdoll.png',
      stats: { armorValue: 1 },
      value: 0,
      description: 'A battle-worn hauberk carried back from distant campaigns.',
    },
    {
      id: 'body_11',
      displayName: 'Hardened Leather Cuirass',
      slot: 'body',
      type: 'medium',
      baseName: 'Medieval_Warfare_Male_Top_2',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Top_2_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Top_2_Paperdoll.png',
      stats: { armorValue: 1 },
      value: 0,
      description: 'A shaped leather breastplate hardened in oil and flame.',
    },
    {
      id: 'body_12',
      displayName: 'Iron-Link Mail',
      slot: 'body',
      type: 'heavy',
      baseName: 'Medieval_Warfare_Male_Top_3',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Top_3_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Top_3_Paperdoll.png',
      stats: { armorValue: 1 },
      value: 0,
      description: 'Interlocking iron rings woven into a dense protective coat.',
    },
    {
      id: 'body_13',
      displayName: 'Highland Skirmisher\'s Brigandine',
      slot: 'body',
      type: 'heavy',
      baseName: 'Medieval_Warfare_Male_Top_4',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Top_4_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Top_4_Paperdoll.png',
      stats: { armorValue: 1 },
      value: 0,
      description: 'Small iron plates riveted inside cloth, worn by mountain fighters.',
    },
    {
      id: 'body_14',
      displayName: 'Veteran\'s Plated Gambeson',
      slot: 'body',
      type: 'heavy',
      baseName: 'Medieval_Warfare_Male_Top_5',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Top_5_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Top_5_Paperdoll.png',
      stats: { armorValue: 1 },
      value: 0,
      description: 'A quilted gambeson reinforced with sewn-in steel plates.',
    },
    {
      id: 'body_15',
      displayName: 'Chainmail',
      slot: 'body',
      type: 'medium',
      baseName: 'Medieval_Warfare_Male_Top_6',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Top_6_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Top_6_Paperdoll.png',
      stats: { armorValue: 1 },
      value: 0,
      description: 'A classic coat of interlocked rings, trusted across centuries of warfare.',
    },
    {
      id: 'body_16',
      displayName: 'Hunter\'s Vest',
      slot: 'body',
      type: 'medium',
      baseName: 'Medieval_Warfare_Male_Top_7',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Top_7_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Top_7_Paperdoll.png',
      stats: { armorValue: 1 },
      value: 0,
      description: 'A practical leather vest with ample pockets for tools and supplies.',
    },
  ],
  bottom: [
    {
      id: 'bottom_1',
      displayName: 'Splint Greaves',
      slot: 'bottom',
      type: 'medium',
      baseName: 'Medieval_Warfare_Male_Bottom_1',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Bottom_1_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Bottom_1_Paperdoll.png',
      stats: { armorValue: 1 },
      value: 0,
      description: 'Metal strips strapped to leather, protecting the legs without sacrificing flexibility.',
    },
    {
      id: 'bottom_2',
      displayName: 'Hardened Leather Chaps',
      slot: 'bottom',
      type: 'medium',
      baseName: 'Medieval_Warfare_Male_Bottom_2',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Bottom_2_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Bottom_2_Paperdoll.png',
      stats: { armorValue: 1 },
      value: 0,
      description: 'Tough leather leg guards shaped to the wearer\'s form.',
    },
    {
      id: 'bottom_3',
      displayName: 'Stalker\'s Trousers',
      slot: 'bottom',
      type: 'light',
      baseName: 'Medieval_Warfare_Male_Bottom_3',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Bottom_3_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Bottom_3_Paperdoll.png',
      stats: { armorValue: 1 },
      value: 0,
      description: 'Lightweight trousers designed for silent movement through dense terrain.',
    },
    {
      id: 'bottom_4',
      displayName: 'Plated Greaves',
      slot: 'bottom',
      type: 'heavy',
      baseName: 'Medieval_Warfare_Male_Bottom_4',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Bottom_4_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Bottom_4_Paperdoll.png',
      stats: { armorValue: 1 },
      value: 0,
      description: 'Solid steel plates encasing the legs for maximum lower-body protection.',
    },
  ],
  feet: [
    {
      id: 'feet_1',
      displayName: 'Leather Boots',
      slot: 'feet',
      type: 'light',
      baseName: 'Medieval_Warfare_Male_Feet_1',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Feet_1_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Feet_1_Paperdoll.png',
      stats: { armorValue: 1 },
      value: 0,
      description: 'Sturdy leather boots suited for long marches and rough terrain.',
    },
    {
      id: 'feet_2',
      displayName: 'Strapped Boots',
      slot: 'feet',
      type: 'medium',
      baseName: 'Medieval_Warfare_Male_Feet_2',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Feet_2_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Feet_2_Paperdoll.png',
      stats: { armorValue: 1 },
      value: 0,
      description: 'Reinforced boots with additional leather strapping for ankle support.',
    },
  ],
  weapon: [
    {
      id: 'weapon_1',
      displayName: 'Matchlock Arquebus',
      slot: 'weapon',
      type: 'ranged',
      hands: 'two-handed',
      baseName: 'Medieval_Warfare_Male_Weapon_Arquebus',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Weapon_Arquebus_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Weapon_Arquebus_Paperdoll.png',
      stats: { damageValue: 1 },
      value: 0,
      description: 'A slow-loading but devastating early firearm that can pierce heavy armor.',
    },
    {
      id: 'weapon_2',
      displayName: 'Recurve Composite Bow',
      slot: 'weapon',
      type: 'ranged',
      hands: 'two-handed',
      baseName: 'Medieval_Warfare_Male_Weapon_Bow',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Weapon_Bow_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Weapon_Bow_Paperdoll.png',
      stats: { damageValue: 1 },
      value: 0,
      description: 'A powerful layered bow that delivers arrows with great speed and force.',
    },
    {
      id: 'weapon_3',
      displayName: 'Soldier\'s Arming Sword',
      slot: 'weapon',
      type: 'melee',
      hands: 'one-handed',
      baseName: 'Medieval_Warfare_Male_Weapon_CrosshiltSword',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Weapon_CrosshiltSword_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Weapon_CrosshiltSword_Paperdoll.png',
      stats: { damageValue: 1 },
      value: 0,
      description: 'The standard sidearm of a trained soldier, reliable and well-balanced.',
    },
    {
      id: 'weapon_4',
      displayName: 'Vanguard Twin-Axe',
      slot: 'weapon',
      type: 'melee',
      hands: 'two-handed',
      baseName: 'Medieval_Warfare_Male_Weapon_Doubleaxe',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Weapon_Doubleaxe_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Weapon_Doubleaxe_Paperdoll.png',
      stats: { damageValue: 1 },
      value: 0,
      description: 'Dual hand axes wielded by aggressive front-line warriors.',
    },
    {
      id: 'weapon_5',
      displayName: 'Heavy Flanged Mace',
      slot: 'weapon',
      type: 'melee',
      hands: 'one-handed',
      baseName: 'Medieval_Warfare_Male_Weapon_FlangedMace',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Weapon_FlangedMace_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Weapon_FlangedMace_Paperdoll.png',
      stats: { damageValue: 1 },
      value: 0,
      description: 'A crushing weapon with protruding flanges designed to dent and deform armor.',
    },
    {
      id: 'weapon_6',
      displayName: 'Garrison Halberd',
      slot: 'weapon',
      type: 'melee',
      hands: 'two-handed',
      baseName: 'Medieval_Warfare_Male_Weapon_Halberd',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Weapon_Halberd_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Weapon_Halberd_Paperdoll.png',
      stats: { damageValue: 1 },
      value: 0,
      description: 'A pole weapon combining an axe blade and spear tip for versatile reach.',
    },
    {
      id: 'weapon_7',
      displayName: 'Knightly Longsword',
      slot: 'weapon',
      type: 'melee',
      hands: 'one-handed',
      baseName: 'Medieval_Warfare_Male_Weapon_Longsword',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Weapon_Longsword_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Weapon_Longsword_Paperdoll.png',
      stats: { damageValue: 1 },
      value: 0,
      description: 'A masterwork blade balanced for both cutting and thrusting in tight formation.',
    },
    {
      id: 'weapon_8',
      displayName: 'Spiked Footman\'s Mace',
      slot: 'weapon',
      type: 'melee',
      hands: 'one-handed',
      baseName: 'Medieval_Warfare_Male_Weapon_Mace',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Weapon_Mace_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Weapon_Mace_Paperdoll.png',
      stats: { damageValue: 1 },
      value: 0,
      description: 'A short heavy mace with iron spikes that punish armored foes.',
    },
    {
      id: 'weapon_9',
      displayName: 'Frontline Pike',
      slot: 'weapon',
      type: 'melee',
      hands: 'two-handed',
      baseName: 'Medieval_Warfare_Male_Weapon_Pike',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Weapon_Pike_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Weapon_Pike_Paperdoll.png',
      stats: { damageValue: 1 },
      value: 0,
      description: 'A long spear designed for disciplined formations, lethal against cavalry.',
    },
    {
      id: 'weapon_10',
      displayName: 'Crow\'s Beak Warhammer',
      slot: 'weapon',
      type: 'melee',
      hands: 'one-handed',
      baseName: 'Medieval_Warfare_Male_Weapon_Warhammer',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Weapon_Warhammer_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Weapon_Warhammer_Paperdoll.png',
      stats: { damageValue: 1 },
      value: 0,
      description: 'A hammer with a curved pick end that punches through plate armor.',
    },
    {
      id: 'weapon_11',
      displayName: 'Steel-Prod Crossbow',
      slot: 'weapon',
      type: 'ranged',
      hands: 'two-handed',
      baseName: 'Medieval_Warfare_Male_Weapon_Xbow',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Weapon_XBow_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Weapon_XBow_Paperdoll.png',
      stats: { damageValue: 1 },
      value: 0,
      description: 'A powerful crossbow with a steel prod that drives bolts through gaps in armor.',
    },
    {
      id: 'weapon_12',
      displayName: 'Landsknecht Zweihander',
      slot: 'weapon',
      type: 'melee',
      hands: 'two-handed',
      baseName: 'Medieval_Warfare_Male_Weapon_Zweihander',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Weapon_Zweihander_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Weapon_Zweihander_Paperdoll.png',
      stats: { damageValue: 1 },
      value: 0,
      description: 'A massive two-handed sword wielded by elite mercenary warriors.',
    },
  ],
  offhand: [
    {
      id: 'offhand_1',
      displayName: 'Parrying Arming Sword',
      slot: 'offhand',
      type: 'melee',
      baseName: 'Medieval_Warfare_Male_Weapon_CrosshiltSword',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Weapon_CrosshiltSword_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Weapon_CrosshiltSword_Paperdoll.png',
      stats: { armorValue: 1, blockChance: 1 },
      value: 0,
      description: 'A shorter blade kept in the off-hand to deflect and counter incoming strikes.',
    },
    {
      id: 'offhand_2',
      displayName: 'Offhand Flanged Mace',
      slot: 'offhand',
      type: 'melee',
      baseName: 'Medieval_Warfare_Male_Weapon_FlangedMace',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Weapon_FlangedMace_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Weapon_FlangedMace_Paperdoll.png',
      stats: { armorValue: 1, blockChance: 1 },
      value: 0,
      description: 'A compact flanged mace used to batter through shields and armor.',
    },
    {
      id: 'offhand_3',
      displayName: 'Companion Longsword',
      slot: 'offhand',
      type: 'melee',
      baseName: 'Medieval_Warfare_Male_Weapon_Longsword',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Weapon_Longsword_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Weapon_Longsword_Paperdoll.png',
      stats: { armorValue: 1, blockChance: 1 },
      value: 0,
      description: 'A longsword wielded in the off-hand by masters of two-sword technique.',
    },
    {
      id: 'offhand_4',
      displayName: 'Curb Spiked Mace',
      slot: 'offhand',
      type: 'melee',
      baseName: 'Medieval_Warfare_Male_Weapon_Mace',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Weapon_Mace_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Weapon_Mace_Paperdoll.png',
      stats: { armorValue: 1, blockChance: 1 },
      value: 0,
      description: 'A brutal spiked mace that punishes any opening left by an opponent.',
    },
    {
      id: 'offhand_5',
      displayName: 'Royal Shield',
      slot: 'offhand',
      type: 'heavy',
      baseName: 'Medieval_Warfare_Male_Shield_1',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Shield_1_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Shield_1_Paperdoll.png',
      stats: { armorValue: 1, blockChance: 1 },
      value: 0,
      description: 'A large heraldic shield bearing royal insignia, offering excellent coverage.',
    },
    {
      id: 'offhand_6',
      displayName: 'Buckler',
      slot: 'offhand',
      type: 'light',
      baseName: 'Medieval_Warfare_Male_Shield_2',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Shield_2_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Shield_2_Paperdoll.png',
      stats: { armorValue: 1, blockChance: 1 },
      value: 0,
      description: 'A small fist-held shield used primarily to deflect and redirect blows.',
    },
    {
      id: 'offhand_7',
      displayName: 'Aquila Kite Shield',
      slot: 'offhand',
      type: 'heavy',
      baseName: 'Medieval_Warfare_Male_Shield_3',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Shield_3_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Shield_3_Paperdoll.png',
      stats: { armorValue: 1, blockChance: 1 },
      value: 0,
      description: 'A large kite-shaped shield bearing the eagle crest, favored by cavalry.',
    },
    {
      id: 'offhand_8',
      displayName: 'Green Scutum',
      slot: 'offhand',
      type: 'medium',
      baseName: 'Medieval_Warfare_Male_Shield_4',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Shield_4_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Shield_4_Paperdoll.png',
      stats: { armorValue: 1, blockChance: 1 },
      value: 0,
      description: 'A rectangular infantry shield with a central boss for punching through formations.',
    },
    {
      id: 'offhand_9',
      displayName: 'Crusader\'s Kite Shield',
      slot: 'offhand',
      type: 'heavy',
      baseName: 'Medieval_Warfare_Male_Shield_5',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Shield_5_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Shield_5_Paperdoll.png',
      stats: { armorValue: 1, blockChance: 1 },
      value: 0,
      description: 'A heavy kite shield marked with crusader iconography.',
    },
    {
      id: 'offhand_10',
      displayName: 'Spiked Round Shield',
      slot: 'offhand',
      type: 'light',
      baseName: 'Medieval_Warfare_Male_Shield_6',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Shield_6_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Shield_6_Paperdoll.png',
      stats: { armorValue: 1, blockChance: 1 },
      value: 0,
      description: 'A round shield fitted with a central spike that turns defense into offense.',
    },
    {
      id: 'offhand_11',
      displayName: 'Oak Heater Shield',
      slot: 'offhand',
      type: 'light',
      baseName: 'Medieval_Warfare_Male_Shield_7',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Shield_7_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Shield_7_Paperdoll.png',
      stats: { armorValue: 1, blockChance: 1 },
      value: 0,
      description: 'A simple triangular shield carved from dense oak wood.',
    },
    {
      id: 'offhand_12',
      displayName: 'Oak Kite Shield',
      slot: 'offhand',
      type: 'light',
      baseName: 'Medieval_Warfare_Male_Shield_8',
      paperdollPath: 'assets/icons/cropped/Medieval_Warfare_Male_Shield_8_Paperdoll.png',
      paperdollPathFull: 'assets/icons/uncropped/Medieval_Warfare_Male_Shield_8_Paperdoll.png',
      stats: { armorValue: 1, blockChance: 1 },
      value: 0,
      description: 'A large wooden kite shield reinforced with iron banding.',
    },
  ],
};

export function getItemPaths(item) {
  const base = `assets/armory/${item.slot}`;
  return {
    idle:    `${base}/${item.slot}_idle/${item.baseName}_idle1_diag.png`,
    walking: `${base}/${item.slot}_walking/${item.baseName}_walking_diag.png`,
    attack1: `${base}/${item.slot}_attacking/${item.baseName}_MVsv_alt_attack1.png`,
    attack2: `${base}/${item.slot}_attacking/${item.baseName}_MVsv_alt_attack2.png`,
  };
}
